### ISSUE TITLE
PPA for Ubuntu

### ISSUE THREAD

**Issue by Symbian9** [KmolYuan/Pyslvs-PyQt5#1]
Please, make PPA with ready to use DEB's for Ubuntu 14.04 and newer.
* https://help.launchpad.net/Packaging/PPA

**Comment by KmolYuan** [comment]
Sorry, I will put it on later.

One of the reasons is that I am currently developing on Ubuntu 16.04 and Windows platforms, and I do not know much about compatibility.

Another reason is that it will take some time to focus on the stability of the program and write the relevant research reports.

I will upload the tested .deb installer in the recently released version.

Thanks for your support!
