### ISSUE TITLE
Ubuntu 17.10 does not show motion paths

### ISSUE THREAD

**Issue by njhurst** [KmolYuan/Pyslvs-PyQt5#12]
I can not work out how to enable the green linkage paths:
![screenshot from 2018-03-04 10-41-56](https://user-images.githubusercontent.com/427287/36949113-cea4c32c-1f98-11e8-8a89-ad94097e376d.png)

Are those green paths expected to show?  As far as I can tell, I've installed all the correct dependencies.

(compare with https://github.com/KmolYuan/Pyslvs-PyQt5/raw/master/images/main_plasma.png)

**Comment by KmolYuan** [comment]
I must say I forgot to add a description for this feature.

I will put it to readme file later.

![](https://user-images.githubusercontent.com/10264720/36955580-47431d4e-2064-11e8-8824-947747417f96.png)

User can driving joints from "inputs" tab. Select a base link and a drive link could add the dependent into variables list, then using QDial widget (it just like a turntable) to adjust the angle value.

Path data will start append coordinates (between a certain of distance) after press the "record" button. Press "record" button again to stop recording.

At the last, path data can be copy or switch visibility by right-click menu.
