### ISSUE TITLE
Compilation error on Mac OSX - symbol(s) not found

### ISSUE THREAD

**Issue by matthieu-lapeyre** [KmolYuan/Pyslvs-PyQt5#17]
Hi,

I would like to try your software but I get the following error during compilation (make build-kernel):

```
[...]
 slvs_wrap.o
      SWIG_Py_Void() in slvs_wrap.o
      SWIG_Python_NewShadowInstance(SwigPyClientData*, _object*) in slvs_wrap.o
      SWIG_Python_AppendOutput(_object*, _object*) in slvs_wrap.o
  "__Py_NotImplementedStruct", referenced from:
      SwigPyObject_richcompare(SwigPyObject*, SwigPyObject*, int) in slvs_wrap.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [_slvs.so] Error 1
make: *** [build-solvespace] Error 2
```

I tried few workaround with no success. Any idea ?

**Comment by KmolYuan** [comment]
I have not test Pyslvs yet on Mac OS, there might be something wrong when I try to catching library path and include path of Python:

<https://github.com/KmolYuan/python-solvespace/blob/master/Makefile#L82>

**Comment by KmolYuan** [comment]
Already added command to build standalong executable files(99df1f848708a622dd6298ee83cc9ad2c309593d) by PyInstaller.

More information can see the section of readme file.
