### ISSUE TITLE
AppImage builds for Linux

### ISSUE THREAD

**Issue by Symbian9** [KmolYuan/Pyslvs-PyQt5#3]
@KmolYuan, thank you for the DEB's produced for KUbuntu 16.04, but it look little incomplete (no dependency information included)

What about producing AppImages, that could run on near all Linux-based distributives?

@probonopd, please, take a look and give an instructon how produce AppImage for **Pyslvs** under KUbuntu 16.04

* https://github.com/KmolYuan/Pyslvs-PyQt5/releases

**Comment by probonopd** [comment]
Thanks @Symbian9 for your interest in AppImage. Please have a look at 
* https://github.com/AppImage/AppImageKit/wiki/
* https://github.com/AppImage/AppImageKit/wiki/Bundling-Python-apps

**Comment by probonopd** [comment]
Thanks @Symbian9 for your interest in AppImage. Please have a look at 
* https://github.com/AppImage/AppImageKit/wiki/
* https://github.com/AppImage/AppImageKit/wiki/Bundling-Python-apps

**Comment by Symbian9** [comment]
@KmolYuan, add fresh binary for Linux in "Releases" section, please!

**Comment by KmolYuan** [comment]
I will try it with virtualenv.

+ https://github.com/probonopd/AppImages/blob/master/recipes/pythongtk3hello/Recipe

**Comment by KmolYuan** [comment]
Add a shell script to "build" the AppImage.

+ https://github.com/KmolYuan/Pyslvs-PyQt5/blob/dev0.9/appimage_recipe.sh

I also update a AppImage to version 0.8.1 release page.

**Comment by probonopd** [comment]
Thanks for providing an AppImage. Unfortunately the desktop file inside the AppImage does not pass validation with `desktop-file-validate`:

```
pyslvs.desktop: error: file contains key "VERSION" in group "Desktop Entry", but keys extending the format should start with "X-"

pyslvs.desktop: error: required key "Type" in group "Desktop Entry" is not present
```

**Comment by KmolYuan** [comment]
I made some small mistakes.

The Version and Type parameters was updated.
