### ISSUE TITLE
"bata" (typo mistake in versioning)

### ISSUE THREAD

**Issue by Symbian9** [KmolYuan/Pyslvs-PyQt5#4]
> Version 0.9 bata 1

This typo mistake should be fixed to "Version 0.9 beta 1". But I also recommend write it as "Pyslvs-PyQt5 0.9-beta.1", and as tag use `v0.9-beta.1`

Also recommend you read the guide "Semantic Versioning"
* http://semver.org

"Semantic Versioning" now is most popular versioning sheme for user software.

### REFERENCE
* https://www.sitepoint.com/semantic-versioning-why-you-should-using/
* https://gist.github.com/jashkenas/cbd2b088e20279ae2c8e
* https://en.wikipedia.org/wiki/Software_versioning

**Comment by KmolYuan** [comment]
OK. Later versions will use this rule.

**Comment by KmolYuan** [comment]
This package is not currently complete, so it will not update the major version.

So maybe minor version changes will not in a backwards-compatible manner.
