### ISSUE TITLE
Can't Maximize program window

### ISSUE THREAD

**Issue by Symbian9** [KmolYuan/Pyslvs-PyQt5#5]
When try Maximize (Ctrl+Alt+5) program window size of it just freezed.

The only way to change window is manually drag each windowborder or use "Filex -> Full screen (Shift+F1)"

Pyslvs: v0.9.0(beta3)
OS: Linux Mint 18 Xfce (64bit)

**Comment by KmolYuan** [comment]
That's strange. I'll try to find out the reason.

I was removed corner widget of menu bar, because it can't show normally in Unity desktop.

Another problem is that full screen window can't hide with "show desktop" function key in Plasma desktop.

**Comment by KmolYuan** [comment]
This problem is also happened in Debian 9.3.

**Comment by Symbian9** [comment]
> This problem is also happened in Debian 9.3.

Yeah, I now try it on *MXLinux MX-17* (based on Debian 9) and this issue reproducable...

**Comment by KmolYuan** [comment]
I found that if screen resolution can not be able to contain the window, it will be not able to maximize in Gnome desktop. Eric IDE has same problem.

If we remove the minimum size limitation of window, all widgets can be extruded to avoid this situation (621b00c31abff1ad0d74b280274ad6855725e249, 0a05c23688787b4c39f82ea23fd1687bfb2e8f93). Eric is also take a similar approach.

Or the screen need to choose a higher resolution.
