### ISSUE TITLE
Can't run AppImage on MX Linux (based on Debian)

### ISSUE THREAD

**Issue by Symbian9** [KmolYuan/Pyslvs-PyQt5#6]
Its look like latest AppImage require some addotional dependency

```
$ ./pyslvs-0.9-beta.3.glibc2.17-x86_64.AppImage
zenity, kdialog, Xdialog missing. ...
```

Is it possible bundle those dependency into AppImage or fully remove those dependency?

OS: MX-17 (x86_64)
- https://mxlinux.org/download-links

**Comment by KmolYuan** [comment]
This dependency is used to create the dialog of AppImage, unless to write a own one.

#https://github.com/AppImage/AppImageKit/issues/340
