### ISSUE TITLE
AppImage is defective

### ISSUE THREAD

**Issue by Symbian9** [KmolYuan/Pyslvs-PyQt5#8]
As @probonopd said

> The AppImage should be made in a way that Python and all of its modules are loaded from within the AppImage. Nothing from the system should be used

### REFERENCE

- https://github.com/AppImage/AppImages/issues/305#issuecomment-361331415
- https://github.com/KmolYuan/Pyslvs-PyQt5/issues/7#issuecomment-361331221

**Comment by KmolYuan** [comment]
Forgot `--always-copy` argument of virtualenv. Always copy files rather than symlinking.
